# Generated by Django 2.1.7 on 2019-03-20 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='bid',
            name='winner_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bid',
            name='winner_email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auctionitem',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='emailqueue',
            name='auction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bid.AuctionItem'),
        ),
        migrations.AddField(
            model_name='emailqueue',
            name='bid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bid.Bid'),
        ),
    ]
