# Generated by Django 2.1.7 on 2019-03-20 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0002_auto_20190320_0724'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='winner_email_sent',
            new_name='email_sent',
        ),
        migrations.RenameField(
            model_name='bid',
            old_name='winner_email_sent_at',
            new_name='email_sent_at',
        ),
    ]
