# Generated by Django 2.1.7 on 2019-03-20 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0005_auto_20190320_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionitem',
            name='bid_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='auctionitem',
            name='current_highest_bid',
            field=models.FloatField(default=100),
        ),
    ]
