# Generated by Django 2.1.7 on 2019-03-20 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0006_auto_20190320_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailqueue',
            name='auction',
        ),
        migrations.RemoveField(
            model_name='emailqueue',
            name='bid',
        ),
        migrations.DeleteModel(
            name='EmailQueue',
        ),
    ]
